spring:
  application:
    name: filtering-redis

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_URL:jdbc:postgresql://localhost:5432/jobs}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:кщще}

  jpa:
    properies:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}