insert into jobs (vacancy_name, company_name, salary, currency) values
    ('Java developer', 'IT', 103000, 'rub'),
    ('Java developer', 'TopCompany', 154000, 'rub'),
    ('Java/Kotlin developer', 'Foreign', 5400, 'usd'),
    ('IOS developer', 'Ops', 4000, 'eur'),
    ('PHP developer', 'IT', 156000, 'rub'),
    ('PHP developer', 'TopCompany', 107000, 'rub'),
    ('Android developer', 'TopCompany', 200000, 'rub'),
    ('Java QA', 'IT', 45000, 'rub'),
    ('Java QA', 'IT', 98000, 'rub'),
    ('Android/Kotlin QA', 'Foreign', 2300, 'eur'),
    ('Project manager', 'Foreign', 5000, 'usd'),
    ('IOS QA', 'IT', 87000, 'rub'),
    ('Project manager', 'Foreign', 4500, 'eur'),
    ('PM', 'IT', 3000, 'eur'),
    ('Java developer', 'TopCompany', 90000, 'rub'),
    ('Junior frontend developer', 'IT', 700, 'eur'),
    ('Frontend developer', 'Ops', 145000, 'rub'),
    ('Product owner', 'TopCompany', 300000, 'rub'),
    ('Project manager', 'IT', 80000, 'rub');
